### ISSUE TITLE
Do you answer questions?

### ISSUE THREAD

**Issue by FrancoCorleone** [AuScalableDroneCloud/metashape-docker#1]
Hey I wonder if you answer questions about your project? I'm trying to dockerize Metashape for some experiments with it, and stumbled upon this repo. 
Let me know!
Greetings

**Comment by OKaluza** [comment]
Hi, sure ask away, this image is in use for us and seems run fine, with GPU support working.
The things you need to change are just the server address and license setup.

**Comment by FrancoCorleone** [comment]
Ok I have couple actually, some may seem dumb to you, sorry in advance.
1. How do you deal with the fact, that floating license server is node-locked? I got a short trial from Agisoft, but I run the server in docker, tried to activate it, and then after I killed off docker container, I also lost this license, as I can't deactivate it anymore... 
2. You have three separate Dockerfiles. Dockerfile.license is RLM server as I can see - from question (1), but then you have two additional ones? Is one of them node-locked or is it some network specific setup?
3. How are you running your setup? Is my assumption correct (judging by svc.cluster.local) that you run those in Kubernetes cluster? Out of curiosity, how many instances do you have on at the same time?
4. The last but not least, any reason you're starting from vulkan image instead of just nvidia cuda?

Greetings,
Jed

**Comment by OKaluza** [comment]
Hi Jed, no worries, 

1. I should have mentioned what is working for us doesn't really include the attempt to dockerise the license server, which failed, because of the issue you mentioned. I still had the stopped container on the vm so I just restarted it and continue to use that. If things go wrong and we lose the vm we'll have to contact AgiSoft, so the image sort of works but you can't just stop it and start a new instance so lose all the benefit of having it in a container. The fact that the license server itself requires a node locked license is frustrating to say the least.
2. Dockerfile.server is to run the Metashape network server process, it doesn't have to run in a separate container but we are doing so, it doesn't need a license or gpu access and just runs in a small vm node.
3. Yes, the intention was to move everything to Kubernetes on OpenStack Magnum, but due to issues in 1. the license server and some other bits and pieces are still just running on plain OpenStack vms. At the moment we have 4 processing nodes, but it's scalable.
4. One of the Metashape processing steps uses the Vulkan API to speed things up rather than CUDA/OpenCL, from memory I think it was the mesh texture generation stage.

**Comment by FrancoCorleone** [comment]
I see, I have similar feelings about this, and it didn't help when I saw that RLM probably wasn't changed since 2015 :D At least that's what Copyrights at the main page says. Weird.

Ad3. So it looks like you have your own hosted environment. Did you research any cloud solutions like AWS, Azure, GCP? In some cases one could run and kill of resources as needed so possibly the cost of the infrastructure could be low if you just experience spikes instead of steady workload. 

Thanks for all responses :)

**Comment by OKaluza** [comment]
We are building our services with tools that would allow leveraging any provider that supports Kubernetes, but our funding includes a decent allocation of hardware on our own Australian research cloud https://ardc.edu.au/services/nectar-research-cloud/ which is powered by OpenStack, we don't have to manage deploying this whole environment ourselves we just issue a few commands and get a running k8s cluster.
I think you are right that scaling by demand is a good approach for this kind of service, but we have other needs for ML workflows etc that will utilise this baseline hardware, if demand takes off we can scale it up further with commercial cloud providers.

**Comment by FrancoCorleone** [comment]
I see, totally makes sense. Is your platform online so I could have a look and admire? Some kind of demo of course, nothing confidential ;)

**Comment by FrancoCorleone** [comment]
I also wonder about this: I tested my workflow with two different EC2 instances, Tesla T4 and V100. One is like 70cents/hr and the other 3USD/hr. Surprisingly, the cheaper one performed a bit better o_O I used the dedicated NVidia AMI and stuff to enable GPU support and stuff, yet got such weird results. I also got better results on my M1 macbook pro! :D 
Did you observe any performance limitations when using docker with this?

**Comment by FrancoCorleone** [comment]
If you have time I wanted to ask you one more thing. I noticed something weird about running metashape in docker. If I run it with metashape -r option, it works fine. But when I try to run a python wrapper, it always ends with Segmentation fault. Funnily enough, it runs fine, everything is created. Just finished with segfault. Did you experience any problems like those?

**Comment by OKaluza** [comment]
Hi Jed, sorry about the slow response - regarding running Metashape with python, that was not heavily tested so could well be broken in the docker image, I did some initial tests with basic scripts and things seemed to work though.

Thanks for the earlier info about profiling, that is concerning! Will look into it at some point if we get time to work more on the Metashape deployment, but I didn't notice any performance problems in my earlier testing. It's hard for me to answer questions because I'm not actively working on this any more, we held of on deploying the metashape stuff for a while, some of the requirements (licensing, needing a shared volume etc) are going to be difficult for us to manage on the scale we need, so haven't actually done much profiling. There is so much happening in the ML based photogrammetry space etc at the moment too that we don't want to invest too much time in one commercial package based pipeline.
We're mostly using WebODM for now which is a really nice project and while not as polished as metashape is improving all the time and is proving much easier to automate and scale. If you want to try it out you can find it at https://asdc.cloud.edu.au.

**Comment by OKaluza** [comment]
Hi, sure happy to help if I can. We're using this image and it's working
for us.
